Parametrize kogito groupId
quarkusio/quarkus-quickstarts pull request #1070
Opened 2022-03-03 09:58 UTC by pjgg

**Check list**:

Your pull request:

- [X ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

2022-03-03 10:48 UTC, rsvoboda requested changes
I would prefer properties names sync similar to the quarkus ones.

@gsmet what is your preference?

2022-03-03 10:48 UTC, rsvoboda commented on kogito-dmn-quickstart/pom.xml
> +        <quarkus.kogito.artifact-id>kogito-quarkus-bom</quarkus.kogito.artifact-id>
What about vvv to be in sync with quarkus platform properties ...
```suggestion
        <kogito.platform.artifact-id>kogito-quarkus-bom</kogito.platform.artifact-id>
```

2022-03-03 10:48 UTC, rsvoboda commented on kogito-dmn-quickstart/pom.xml
>          <kogito-quarkus.version>1.16.1.Final</kogito-quarkus.version>
An maybe `kogito.platform.version`

2022-03-05 14:20 UTC, gsmet approved these changes

2022-03-05 14:21 UTC, merged