Update security-openid-connect-multi-tenancy-quickstart to use Keycloak 17.0.0-legacy image
quarkusio/quarkus-quickstarts pull request #1085
Opened 2022-03-16 21:46 UTC by sberyozkin

At the moment a WildFly based distro needs to be used for now because we can't test it with Dev Services for Keycloak because it won;t work with multiple tenants, while Quarkus based distro does not support importing the realms from the file/class path - realms have to be read and uploaded using KC AdminClient API (which is what Dev Services for Keycloak does) but it would be too complex for a test setup for the new users to see

2022-03-17 09:04 UTC, rsvoboda requested changes

2022-03-17 09:04 UTC, rsvoboda commented on security-openid-connect-multi-tenancy-quickstart/pom.xml
> +        <keycloak.version>17.0.0</keycloak.version>
My preference is to be explicit in version definition
```suggestion
        <keycloak.version>17.0.0-legacy</keycloak.version>
```

2022-03-17 09:04 UTC, rsvoboda commented on security-openid-connect-multi-tenancy-quickstart/src/test/java/org/acme/quickstart/oidc/KeycloakServer.java
> +        keycloak = new FixedHostPortGenericContainer("quay.io/keycloak/keycloak:" + System.getProperty("keycloak.version") + "-legacy")
revert this change pls

2022-03-19 17:05 UTC, gsmet commented
I applied @rsvoboda 's suggestion as I think it makes sense.

The test works but I have:
```
2022-03-19 18:01:42,934 WARN  [org.tes.con.wai.str.HttpWaitStrategy] (pool-4-thread-1) Unexpected error occurred - will proceed to try to wait anyway: java.lang.IllegalStateException: Target port 8180 is not exposed
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$2(HttpWaitStrategy.java:197)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:51)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:929)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:468)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at org.acme.quickstart.oidc.KeycloakServer.start(KeycloakServer.java:27)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:452)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
in the log, which is not pretty.

2022-03-19 18:32 UTC, gsmet approved these changes

2022-03-19 18:32 UTC, merged

2022-03-22 13:12 UTC, sberyozkin commented
@gsmet @rsvoboda apologies I did not comment, I was away most of the weekend/end of last week