Reactive Messaging Pulsar quickstart
quarkusio/quarkus-quickstarts pull request #1292
Opened 2023-06-28 13:01 UTC by ozangunalp

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has integration/native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [x] links the guide update pull request (if needed) https://github.com/quarkusio/quarkus/pull/34378
- [x] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [x] for new quickstart, is added to the root `pom.xml` and `README.md`

2023-06-28 13:40 UTC, cescoffier requested changes

2023-06-28 13:40 UTC, cescoffier commented on pulsar-quickstart/pulsar-quickstart-producer/.htpasswd
> +quarkus:$apr1$klBx1KPJ$WRwoAytYCq3rPirm0mp4l/
Why?

2023-06-28 17:02 UTC, ozangunalp commented on pulsar-quickstart/pulsar-quickstart-producer/.htpasswd
> +quarkus:$apr1$klBx1KPJ$WRwoAytYCq3rPirm0mp4l/
I left it by mistake. Removed it now

2023-07-03 08:01 UTC, merged

2023-07-05 13:36 UTC, gsmet commented
Guys, it's a bad idea to merge 3.3 stuff before I released the quickstarts. I reverted it in what I will publish as the 3.2 quickstarts.

Note: you don't need to do anything, it's just for your awareness.