Revamp AWS Quickstarts with DevServices
quarkusio/quarkus-quickstarts pull request #1356
Opened 2023-12-01 22:54 UTC by scrocquesel

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [x] works in native (`mvn clean package -Pnative`)
- [x] has integration/native tests (`mvn clean verify -Pnative`)
- [x] makes sure the associated guide must not be updated
- [x] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

2023-12-12 11:53 UTC, gsmet requested changes
Thanks for that but changes to the Dockerfiles look incorrect.

2023-12-12 11:53 UTC, gsmet commented on amazon-dynamodb-quickstart/src/main/docker/Dockerfile.jvm
> +# docker run -i --rm -p 8080:8080 quarkus/amazon-ssm-quickstart-jvm
These changes are off.

How did you update these Dockerfiles? We should be updating them automatically on release.

2023-12-23 22:47 UTC, scrocquesel commented
@gsmet kind reminder

2024-01-12 17:19 UTC, gsmet approved these changes
Sorry it slipped, merging now.

Thanks for this awesome work!

2024-01-12 17:19 UTC, merged