Allow injection of SearchSession/SearchMapping
quarkusio/quarkus-quickstarts pull request #725
Opened 2020-12-04 10:31 UTC by yrodiere

Relates to https://github.com/quarkusio/quarkus/pull/13696

**Check list**:

Your pull request:

- [X] targets the `development` branch
- [X] uses the `999-SNAPSHOT` version of Quarkus
- [X] has tests (`mvn clean test`)
- [X] works in native (`mvn clean package -Pnative`)
- [X] has native tests (`mvn clean verify -Pnative`)
- [X] makes sure the associated guide must not be updated
- [X] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

2020-12-08 09:57 UTC, yrodiere commented
@gsmet I restarted the build, now that we've merged https://github.com/quarkusio/quarkus/pull/13696. This PR is ready to merge.

2020-12-08 10:16 UTC, gsmet approved these changes

2020-12-10 16:02 UTC, gsmet requested changes

2020-12-10 16:02 UTC, gsmet commented on hibernate-search-orm-elasticsearch-quickstart/src/main/java/org/acme/hibernate/search/elasticsearch/LibraryResource.java
> +    SearchSession searchSession;
We can remove the `em` field above, can't we?

2020-12-10 16:11 UTC, gsmet approved these changes

2020-12-10 22:33 UTC, merged