Infinspan README updates
quarkusio/quarkus-quickstarts pull request #736
Opened 2020-12-22 13:55 UTC by gunnarmorling

**Check list**:

Your pull request:

- [x] targets the `development` branch
- [x] uses the `999-SNAPSHOT` version of Quarkus
- [x] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

2020-12-22 13:58 UTC, gunnarmorling commented
// CC @gsmet @geoand

2020-12-22 14:03 UTC, geoand approved these changes

2020-12-22 14:26 UTC, gsmet requested changes
Spotted a minor formatting issue. Could you take care of it? Also there's a typo in the commit message.

2020-12-22 14:26 UTC, gsmet commented on infinispan-client-quickstart/README.md
> +property in the `file src/main/resources/META-INF/resources/hotrod-client.properties`: `quarkus.infinispan-client.client-intelligence=BASIC`
```suggestion
property in the file `src/main/resources/META-INF/resources/hotrod-client.properties`: `quarkus.infinispan-client.client-intelligence=BASIC`
```

2020-12-22 15:25 UTC, gunnarmorling commented
Thx, good spot, added your change. Can you just apply the commit message change by squashing both commits?

2021-01-04 15:57 UTC, gsmet approved these changes

2021-01-04 15:58 UTC, merged