use quarkus-micro instead of quarkus-distroless
quarkusio/quarkus-quickstarts pull request #997
Opened 2021-11-30 14:40 UTC by matthyx

**Check list**:

Your pull request:

- [ ] targets the `development` branch
- [ ] uses the `999-SNAPSHOT` version of Quarkus
- [ ] has tests (`mvn clean test`)
- [ ] works in native (`mvn clean package -Pnative`)
- [ ] has native tests (`mvn clean verify -Pnative`)
- [ ] makes sure the associated guide must not be updated
- [ ] links the guide update pull request (if needed)
- [ ] updates or creates the `README.md` file (with build and run instructions)
- [ ] for new quickstart, is located in the directory _component-quickstart_
- [ ] for new quickstart, is added to the root `pom.xml` and `README.md`

2021-11-30 14:40 UTC, matthyx commented
/assign @cescoffier

2021-11-30 14:41 UTC, matthyx commented
/cc @Karm

2021-12-01 09:24 UTC, Karm commented
@matthyx Lemme try the AWT one to see if it survived the migration...

2021-12-02 07:17 UTC, matthyx commented
> @matthyx Lemme try the AWT one to see if it survived the migration...

any update?

2021-12-02 10:05 UTC, Karm requested changes
@matthyx It doesn't work for me :-(

When I go through the motions in `awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native-distroless`

It ends up with:

```
docker: Error response from daemon: unable to find user nonroot: no matching entries in passwd file.
```

2021-12-02 10:08 UTC, matthyx commented
Damn, how can I test it?

2021-12-02 10:13 UTC, Karm commented
@matthyx Well...it's all in the file: awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native-distroless

Is it isolated to this particular quickstart?  I noticed your change:

```
- USER 1001
+ USER nonroot
```

and that expects the new runtime container you are swapping all those containers for to actually have such user created...

2021-12-02 11:06 UTC, matthyx commented
> @matthyx Well...it's all in the file: awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native-distroless
> 
> Is it isolated to this particular quickstart? I noticed your change:
> 
> ```
> - USER 1001
> + USER nonroot
> ```
> 
> and that expects the new runtime container you are swapping all those containers for to actually have such user created...

my mistake, actually should be `1001` everywhere... I will correct later, sorry!

2021-12-02 12:55 UTC, matthyx commented
@Karm fixed, thanks for the review!

2021-12-02 21:59 UTC, Karm commented on awt-graphics-rest-quickstart/src/main/docker/Dockerfile.native-distroless
> -#
@matthyx May I ask you to leave the info there, just deleting 
```
# Using Debian based https://github.com/quarkusio/quarkus-images/blob/main/quarkus-distroless-image.yaml#L16
# will not do for this Quickstart as only libz.so is copied and the runtime
# might not be compatible with Quarkus executable built using UBI image.
```

The pointer about buildah is still relevant. Copying files manually in this fashion does the job for a simple example, for the sake of brevity, but it won't do for any serious long term maintainable project.

2021-12-02 22:01 UTC, Karm approved these changes
Thanks! It works for me as far as AWT quickstart is concerned. 

One note about comment in the Dockerfile. 

Cheers

2021-12-03 06:16 UTC, matthyx commented
> Thanks! It works for me as far as AWT quickstart is concerned.
> 
> One note about comment in the Dockerfile.
> 
> Cheers

I have restored your ASCII art ;-)
Thanks for the review!

@cescoffier PTAL

2021-12-03 11:29 UTC, cescoffier reviewed
I would have changed the file names to micro. Except that looks good to me.

2021-12-06 11:01 UTC, matthyx commented
> I would have changed the file names to micro. Except that looks good to me.

done, sorry for the delay - I hope it's not too late for 2.6

2021-12-06 11:04 UTC, cescoffier approved these changes

2021-12-07 07:08 UTC, merged